// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDJ63eOtyR1ofGzMIy6T1XIKvhGLtu10A',
    appId: '1:496557759827:web:de16e511b530a9349d95a6',
    messagingSenderId: '496557759827',
    projectId: 'ujian-smmks',
    authDomain: 'ujian-smmks.firebaseapp.com',
    storageBucket: 'ujian-smmks.firebasestorage.app',
    measurementId: 'G-4TD50NRFN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANo0zLQAg899E3e9n0mZhktiZwXf-hrVk',
    appId: '1:496557759827:android:f766ffe8f9a4c1c69d95a6',
    messagingSenderId: '496557759827',
    projectId: 'ujian-smmks',
    storageBucket: 'ujian-smmks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM2bSZ0ch41FQJR-9uOqqqYMK3Av7ZsWY',
    appId: '1:496557759827:ios:8c84c2c39f1fdeb59d95a6',
    messagingSenderId: '496557759827',
    projectId: 'ujian-smmks',
    storageBucket: 'ujian-smmks.firebasestorage.app',
    iosBundleId: 'com.example.ujianOnlineSmks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM2bSZ0ch41FQJR-9uOqqqYMK3Av7ZsWY',
    appId: '1:496557759827:ios:8c84c2c39f1fdeb59d95a6',
    messagingSenderId: '496557759827',
    projectId: 'ujian-smmks',
    storageBucket: 'ujian-smmks.firebasestorage.app',
    iosBundleId: 'com.example.ujianOnlineSmks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDJ63eOtyR1ofGzMIy6T1XIKvhGLtu10A',
    appId: '1:496557759827:web:12d4c54129b87cc89d95a6',
    messagingSenderId: '496557759827',
    projectId: 'ujian-smmks',
    authDomain: 'ujian-smmks.firebaseapp.com',
    storageBucket: 'ujian-smmks.firebasestorage.app',
    measurementId: 'G-8ZRVXSM72B',
  );
}
